name: mlflow-iris

services:
  app:
    build: .
    container_name: iris-api
    env_file:
      - .env
    environment:
      # Трекать эксперименты в контейнерном MLflow
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
      - minio
    volumes:
      # Чтобы результаты были видны и на хосте
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports

  minio:
    image: minio/minio:latest
    container_name: minio2
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    image: mlflow-with-boto3:3.6.0
    container_name: mlflow
    depends_on:
      - minio
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_DEFAULT_REGION: us-east-1
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      MLFLOW_S3_IGNORE_TLS: "true"
#      MLFLOW_SERVER_ALLOWED_HOSTS: "mlflow,mlflow:5000,localhost,127.0.0.1"
      # здесь важно, чтобы в .env было указано имя бакета
      # MLFLOW_S3_BUCKET=mlflow-iris  (пример)
    command: >
      mlflow server
        --host 0.0.0.0
        --port 5000
        --backend-store-uri sqlite:////mlflow/mlflow.db
        --artifacts-destination s3://${MLFLOW_S3_BUCKET}
        --allowed-hosts *
        --cors-allowed-origins *
    volumes:
      - ./mlflow_data:/mlflow    # здесь будут mlflow.db и служебные файлы
    ports:
      - "5000:5000"

volumes:
  minio-data:
  mlflow_data:
